name: cloudflare_r2
description: "Dart plugin for Cloudflare R2."
version: 0.0.12
homepage: "https://github.com/rodolfogoulart/cloudflare_r2"

environment:
  sdk: ^3.5.4

dependencies:
  aws_common: ^0.7.4
  aws_signature_v4: ^0.6.3
  intl: '>=0.17.0'
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.1.0